# Generated by Django 5.1 on 2024-09-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_vote_unique_together_remove_vote_voted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
