name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests with Environment Variables
      env:
        DEBUG: 'True'
        SECRET_KEY: 'django-insecure-ci-test-key'
        ALLOWED_HOSTS: 'localhost,127.0.0.1,testserver'
      run: |
        python manage.py test
    - name: Prepare testing.env
      run: |
        echo "DEBUG=True" > testing.env
        echo "SECRET_KEY=django-insecure-ci-test-key-from-file" >> testing.env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1,testserver" >> testing.env
    - name: Run Tests with .env file
      run: |
        mv testing.env .env
        python manage.py test
